spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.211/mall_admin_management?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell